# -*- coding: utf-8 -*-
"""卒業研究2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4qylwIG3Hkf-brLXPXb3dGk_XIcp9S7
"""

import pulp
from pulp import LpProblem, LpVariable, lpSum, LpMinimize, LpBinary, LpContinuous, PULP_CBC_CMD
from pulp import LpStatus
from openpyxl import *
from openpyxl import load_workbook
import os
import openpyxl
import time
import streamlit as st
import pandas as pd
from io import BytesIO

st.title("野球紅白戦チーム分けWEBアプリ")

uploaded_file = st.file_uploader("Excelファイルをアップロードしてください　(.xlsx)", type="xlsx")
if uploaded_file is not None:
  #アップロードされたバイトデータを読み込み
  file_bytes = uploaded_file.read()
  #openpyxlで直接読み込む
  from io import BytesIO
  wb = load_workbook(filename=BytesIO(file_bytes), data_only=True)
  #ここから「book」変数として扱う
  book=wb

  name = '選手データ＆チーム分け結果１'
  try:
    df = pd.read_excel(BytesIO(file_bytes), sheet_name=name, header=1)
    #先頭行、先頭列削除
    #df = df.drop(0).reset_index(drop=True)
    df = df.drop(columns=df.columns[0])
    
    #st.dataframe(df, use_container_width=True)

    #st.write("列順（変更前）：",df.columns.tolist())  

    excel_col_index = 13
    df_col_index = excel_col_index - 1
      
    if len(df.columns) > df_col_index:
        new_cols = df.columns.tolist()
        col14 = new_cols.pop(df_col_index)
        new_cols.insert(2, col14)
        df = df[new_cols]

    excel_col_index_2 = 13
    df_col_index_2 = excel_col_index_2 - 1

    if len(df.columns) > df_col_index_2:
        new_cols_2 = df.columns.tolist()
        col13 = new_cols_2.pop(df_col_index_2)
        new_cols_2.insert(3, col13)
        df = df[new_cols_2]

    #st.write("列順（変更後）：",df.columns.tolist())
    

      
    st.subheader("アップロードされたデータ")
    st.write("出欠：出場…１、欠場…０")
    st.write("打撃力：その選手の打撃力の能力を数値化")
    st.write("守指定（その選手に守らせたいポジション）：１～９（ピッチャー～ライトの守備番号）")
    st.write("投～右（ピッチャー～ライト）：それぞれの守備位置での能力を数値化")

    df = df.dropna(subset=[df.columns[1]])
      
    st.dataframe(df.iloc[:,:13].head(28), use_container_width=True)

    first_col = df.iloc[:,0].copy()
    df_14_after = df.iloc[:,13:]
    df_combined = pd.concat([first_col, df_14_after], axis=1)

    df_combined = df_combined.dropna(subset=[df_combined.columns[1]])

    st.subheader("過去紅白戦のチーム分け結果")
    st.write("0：所属なし、1：チーム１に所属、2：チーム２に所属")
    
    st.dataframe(df_combined.head(27), use_container_width=True)
    
    sheet = book[name]
  except Exception as e:
    st.error(f"読み込み中にエラーが発生しました:{e}")
    st.stop()

  if st.button("チーム分けを実行"):
    with st.spinner("最適化中...少々お待ちください（最長1分ほど）"):
      main_file = '紅白戦結果.xlsx'
      sub_file = '紅白戦.xlsx'
      #name = '選手データ＆チーム分け結果１'

      yomikomi=0
  #2回目以降のファイル読み込み
      if uploaded_file.name == "紅白戦結果.xlsx":
        #book = load_workbook(main_file)
        #st.write("2回目以降の紅白戦")
        yomikomi = 2
        #PP = openpyxl.load_workbook('紅白戦結果.xlsx', data_only = True)
        P_SUM = book[name]
        I_num = P_SUM.max_row - 3
  #1回目のファイル読み込み
      elif uploaded_file.name == "紅白戦.xlsx":
        #book = load_workbook(sub_file)
        #st.write("1回目の紅白戦")
        yomikomi = 1
        #PP = openpyxl.load_workbook('紅白戦.xlsx', data_only = True)
        P_SUM = book[name]
        I_num = P_SUM.max_row - 3
      else:
        st.error("対象ファイルがありません")
        st.stop()

      sheet = book[name]

      J_num = 9
      T_num = 2

      I = [i+1 for i in range(I_num)]
      J = [j+1 for j in range(J_num)]
      T = [t+1 for t in range(T_num)]

      E = {}#出場欠場
      reg = 0
      for i in I:
        if sheet.cell(row=2+i, column=3).value is not None:
          E[i] = sheet.cell(row=2+i, column=3).value
          reg += 1

      EE = 0
      for i in range(1,reg+1):
        EE += E[i]

      P = {}#ポジションの評価値
      for i in range(1,reg+1):
        for j in J:
          P[(i, j)] = sheet.cell(row=2+i, column=3+j).value

      WP = {}#守りたいポジション
      for i in range(1,reg+1):
        WP[i] = sheet.cell(row=2+i, column=13).value


      B = {}#打撃力の評価値
      for i in range(1,reg+1):
        B[(i)] = sheet.cell(row=2+i, column=14).value


      problem = LpProblem('kouhaku', LpMinimize)


      #過去の紅白戦のチーム読み込み
      n_count = 0
      if yomikomi == 2:
        tt = {}
        while sheet.cell(row=3, column=15+n_count).value is not None:
          n_count += 1
        for c in range(1,n_count+1):
            for i in range(1,reg+1):
              tt[i, c] = sheet.cell(row=2+i, column=14+c).value

      sheet = book['チーム分け結果詳細']
      for i_count in range(I_num):
        for t_count in range(10):
          sheet.cell(row=3+i_count, column=3+t_count).value = None

      #一つ前の紅白戦で同じチームの選手は1、そうじゃなければ0
      A = {}
      n = 0
      if yomikomi==2:
          for c in range(1,n_count+1):
            for i in range(1,reg):
              for ii in range(i+1,reg+1):
                if c == 1:
                  A[i, ii] = 0
                if tt[i, c] == tt[ii, c] and tt[i, c] >= 1  and tt[ii, c] >= 1:
                  A[i, ii] += 1
          for i in range(1,reg):
                for ii in range(i+1,reg+1):
                  A[i, ii] = A[i, ii]/n_count
      elif yomikomi==1:
        for i in range(1,reg):
          for ii in range(i+1,reg+1):
            A[i, ii] = 0


      #目的関数
      x = {}
      for i in range(1,reg+1):
        for j in J:
          for t in T:
            if E[i] == 1 and P[(i,j)] > 0:
              x[(i, j, t)] = LpVariable(f'x_{i}_{j}_{t}', cat=LpBinary)


      #iとiiが同じチームであるときに1,そうでないとき0
      Y = {}
      for i in range(1,reg):
        if E[i] == 1:
          for ii in range(i+1,reg+1):
            if E[ii] == 1:
              Y[(i,ii)] = LpVariable(f'y_{i}_{ii}', cat=LpBinary)


      ##制約条件
      #出場する選手が欠場したり、欠場する選手が出場したりすることがない
      for i in range(1,reg+1):
        problem += lpSum(x[(i,j,t)] for j in J for t in T if (i,j,t) in x) == E[i], f"constraint_attend_{i}"

      #チーム振り分けの際に両チームの人数をできるだけ均等にする
      for t in T:
          problem += lpSum(x[i,j,t] for i in range(1,reg+1) for j in J if (i,j,t) in x) >= EE//2, f"constraint_team_size_{t}"

      #1チーム内で各ポジション守れる選手を一人以上選ぶこと
      for j in J:
        for t in T:
          problem += lpSum(x[(i,j,t)] for i in range(1,reg+1) if (i,j,t) in x) >= 1, f"constraint_position_{j}_{t}"

      #1チーム内でピッチャーを守れる選手を2人以上選ぶこと
      count_pitcher = 0
      for i in range(1,reg+1):
        if P[(i,1)] >= 1:
          count_pitcher += 1

      if count_pitcher >= 4:
        for t in T:
          problem += lpSum(x[(i,1,t)] for i in range(1,reg+1) if (i,1,t) in x) >= 2, f"constraint_pitcher_{t}"

      #守らせたいポジションがある選手はそのポジションを守らせる
      for i in range(1,reg+1):
        if WP[i] > 0:#and E[i] == 1:
          problem += lpSum(x[(i,WP[i],t)] for t in T if (i,WP[i],t) in x) == 1, f"constraint_want_pojition_{i}"

      #過去の紅白戦で同じチームになった選手はできるだけ違うチームに振り分ける
      for i in range(1,reg):
        for ii in range(i+1,reg+1):
          for t in T:
            if (i,ii) in Y:
              problem += Y[(i,ii)] >= lpSum(x[(i,j,t)] for j in J if (i,j,t) in x) + lpSum(x[(ii,j,t)] for j in J if (ii,j,t) in x) - 1, f"constraint_prior_same_team_{i}_{ii}_{t}"

      #絶対値
      z = LpVariable('z', lowBound=0, cat=LpContinuous)

      power={}
      for t in T:
        power[t] = lpSum((P[(i,j)]+B[(i)])*(x[(i,j,t)]) for i in range(1,reg+1) for j in J if (i,j,t) in x)

      problem += z >= -(power[1]-power[2]), "constraint_abs1"
      problem += z >= power[1]-power[2], "constraint_abs2"

      #最小化実行
      problem += 100*z + lpSum(A[i,ii]*Y[(i,ii)]for i in range(1,reg) if E[i] == 1 for ii in range(i+1,reg+1) if E[ii] == 1), "Objective"

      problem.writeLP('kouhaku.lp')

      st.write(f"{n_count+1}回目の紅白戦")
      st.write("最適化開始")
      start_time = time.time()
      status = problem.solve(PULP_CBC_CMD(timeLimit=60, msg=True))
      end_time = time.time()
#pulp.LpStatus[status]
      st.write("最適化終了")
      elapsed_time = end_time - start_time
      st.write(f"最適化実行時間: {elapsed_time:.3f}秒")
      st.write(f"ステータス: {pulp.LpStatus[status]}")



#エクセル出力


      t1=0
      t2=0
      p1=0
      p2=0
      b1=0
      b2=0
      if pulp.LpStatus[status] == 'Optimal':
        st.write("結果をExcelに書き込みます...")
        st.write("--------------------")
        for i in range(1,reg+1):
          for j in J:
            for t in T:
              if (i,j,t) in x and x[(i,j,t)].varValue >= 0.99:
                sheet = book[name]
                sheet.cell(row=2+i,column=15+n_count).value = t
                sheet.cell(row=2,column=15+n_count).value = f"{n_count+1}回目"
                sheet = book['チーム分け結果詳細']
                sheet.cell(row=2+i,column=2+(5*t-4)).value = 1
                  
                if t==1:
                    t1 += 1
                elif t==2:
                    t2 += 1
                sheet.cell(row=2+i,column=3+(5*t-4)).value = j
                sheet.cell(row=2+i,column=4+(5*t-4)).value = P[(i,j)]
                if t==1:
                    p1 += P[(i,j)]
                elif t==2:
                    p2 += P[(i,j)]
                sheet.cell(row=2+i,column=5+(5*t-4)).value = B[(i)]
                if t==1:
                    b1 += B[(i)]
                elif t==2:
                    b2 += B[(i)]
                sheet.cell(row=2+i,column=6+(5*t-4)).value = P[(i,j)]+B[(i)]
        
        sheet.cell(row=29,column=3).value = t1
        sheet.cell(row=29,column=5).value = p1
        sheet.cell(row=29,column=6).value = b1
        sheet.cell(row=29,column=7).value = p1+b1
        sheet.cell(row=29,column=8).value = t2
        sheet.cell(row=29,column=10).value = p2
        sheet.cell(row=29,column=11).value = b2
        sheet.cell(row=29,column=12).value = p2+b2

        #sheet.row_dimensions[29].hidden = True
        
        sheet = book[name]
        for i in range(1,reg+1):
          if sheet.cell(row=2+i, column=15+n_count).value is None:
            sheet.cell(row=2+i, column=15+n_count).value = 0


        sheet["C29"] = "=SUM(C3:C28)"

        save_filename = f"紅白戦結果.xlsx"
        #wb.calculation_properties.fullCalcOnLoad = True
        book.save(save_filename)

        if yomikomi == 2:
            #保存
            output_stream = BytesIO()
            book.save(output_stream)
            output_stream.seek(0)

            try:
                df_result = pd.read_excel(output_stream, sheet_name='チーム分け結果詳細', header=1)
            except Exception as e:
                st.error(f"結果読み込み中にエラーが発生しました：{e}")
                st.download_button(
                    label="結果ファイルをダウンロード",
                    data=output_stream.getvalue(),
                    file_name=f"{uploaded_file.name}",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
                st.stop()

            #df_result = df_result.drop(index=0).reset_index(drop=True)
            df_result = df_result.drop(columns=df_result.columns[0])
            
            st.subheader("最適化結果（チーム分け結果）")

            def is_number(x):
                try:
                    float(x)
                    return True
                except:
                    return False



            if len(df_result) > 26:
                row_27 = df_result.iloc[[26]]
            else:
                row_27 = pd.DataFrame(columns=df_result.columns)
                
            mask_1 = df_result.iloc[:, 2].apply(is_number)
            cols_1 = [df_result.columns[0]] + list(df_result.columns[2:6])
            table_1 = df_result.loc[mask_1, cols_1]

            mask_2 = df_result.iloc[:, 6].apply(is_number)
            cols_2 = [df_result.columns[0]] + list(df_result.columns[7:11])
            table_2 = df_result.loc[mask_2, cols_2]

            
            #row_28 = df_result.iloc[[27], cols_1]

            table_1_with_second = pd.concat([table_1], ignore_index=True)

            
            table_2_with_second = pd.concat([table_2], ignore_index=True)

            table_1_with_second_clean = table_1_with_second.dropna(subset=[table_1_with_second.columns[1]])

            table_2_with_second_clean = table_2_with_second.dropna(subset=[table_2_with_second.columns[1]])
            df_display_2 = table_2_with_second_clean.drop(index=[26],errors = 'ignore')

            st.write("ポジション：その選手が守る守備位置（ピッチャー～ライト）")
            st.write("守備力：その選手のポジションでの守備の能力を数値化")
            st.write("打撃力：その選手の打撃の能力を数値化")
            st.write("総合力：その選手の守備力と打撃力の合計")

            st.subheader("チーム１に属する選手")
            st.write(f"チーム1　人数:{t1}、守備力合計:{p1}、打撃力合計:{b1}、総合力合計:{p1+b1}")
            st.dataframe(table_1_with_second_clean, use_container_width=True)

            st.subheader("チーム２に属する選手")
            st.write(f"チーム2　人数:{t2}、守備力合計:{p2}、打撃力合計:{b2}、総合力合計:{p2+b2}")
            st.dataframe(df_display_2, use_container_width=True)


            file_name = "紅白戦結果.xlsx"

            st.download_button(
                label="結果ファイルをダウンロード",
                data=output_stream,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        else:
            #保存
            output_stream = BytesIO()
            book.save(output_stream)
            output_stream.seek(0)

            try:
                df_result = pd.read_excel(output_stream, sheet_name='チーム分け結果詳細', header=1)
            except Exception as e:
                st.error(f"結果読み込み中にエラーが発生しました：{e}")
                st.download_button(
                    label="結果ファイルをダウンロード",
                    data=output_stream.getvalue(),
                    file_name=f"{uploaded_file.name}",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
                st.stop()

            #df_result = df_result.drop(index=0).reset_index(drop=True)
            df_result = df_result.drop(columns=df_result.columns[0])
            
            
            st.subheader("最適化結果（チーム分け結果）")
            def is_number(x):
                try:
                    float(x)
                    return True
                except:
                    return False

            


            if len(df_result) > 26:
                row_27 = df_result.iloc[[26]]
            else:
                row_27 = pd.DataFrame(columns=df_result.columns)
                
            mask_1 = df_result.iloc[:, 2].apply(is_number)
            cols_1 = [df_result.columns[0]] + list(df_result.columns[2:6])
            table_1 = df_result.loc[mask_1, cols_1]

            mask_2 = df_result.iloc[:, 6].apply(is_number)
            cols_2 = [df_result.columns[0]] + list(df_result.columns[7:11])
            table_2 = df_result.loc[mask_2, cols_2]

            
            #row_28 = df_result.iloc[[27], cols_1]

           
            table_1_with_second = pd.concat([table_1], ignore_index=True)

            
            table_2_with_second = pd.concat([table_2], ignore_index=True)
            
            table_1_with_second_clean = table_1_with_second.dropna(subset=[table_1_with_second.columns[1]])

            table_2_with_second_clean = table_2_with_second.dropna(subset=[table_2_with_second.columns[1]])
            df_display_2 = table_2_with_second_clean.drop(index=[26],errors = 'ignore')

            st.write("ポジション：その選手が守る守備位置（ピッチャー～ライト）")
            st.write("守備力：その選手のポジションでの守備の能力を数値化")
            st.write("打撃力：その選手の打撃の能力を数値化")
            st.write("総合力：その選手の守備力と打撃力の合計")
            
            st.subheader("チーム１に属する選手")
            st.write(f"チーム1　人数:{t1}、守備力合計:{p1}、打撃力合計:{b1}、総合力合計:{p1+b1}")
            st.dataframe(table_1_with_second_clean, use_container_width=True)

            st.subheader("チーム２に属する選手")
            st.write(f"チーム2　人数:{t2}、守備力合計:{p2}、打撃力合計:{b2}、総合力合計:{p2+b2}")
            st.dataframe(df_display_2, use_container_width=True)



            file_name = "紅白戦結果.xlsx"

            st.download_button(
                label="結果ファイルをダウンロード",
                data=output_stream,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        




        

      elif elapsed_time >= 60:
        st.write("結果をExcelに書き込みます...")
        st.write("--------------------")
        for i in range(1,reg+1):
          for j in J:
            for t in T:
              if (i,j,t) in x and x[(i,j,t)].varValue >= 0.99:
                sheet = book[name]
                sheet.cell(row=2+i,column=15+n_count).value = t
                sheet.cell(row=2, column=15+n_count).value = n_count+1
                sheet = book['チーム分け結果詳細']
                sheet.cell(row=2+i,column=2+(5*t-4)).value = 1
                if t==1:
                    t1 += 1
                elif t==2:
                    t2 += 1
                sheet.cell(row=2+i,column=3+(5*t-4)).value = j
                sheet.cell(row=2+i,column=4+(5*t-4)).value = P[(i,j)]
                if t==1:
                    p1 += P[(i,j)]
                elif t==2:
                    p2 += P[(i,j)]
                sheet.cell(row=2+i,column=5+(5*t-4)).value = B[(i)]
                if t==1:
                    b1 += B[(i)]
                elif t==2:
                    b2 += B[(i)]
                sheet.cell(row=2+i,column=6+(5*t-4)).value = P[(i,j)]+B[(i)]
        
        sheet.cell(row=29,column=3).value = t1
        sheet.cell(row=29,column=5).value = p1
        sheet.cell(row=29,column=6).value = b1
        sheet.cell(row=29,column=7).value = p1+b1
        sheet.cell(row=29,column=8).value = t2
        sheet.cell(row=29,column=10).value = p2
        sheet.cell(row=29,column=11).value = b2
        sheet.cell(row=29,column=12).value = p2+b2

        #sheet.row_dimensions[29].hidden = True

        sheet = book[name]
        for i in range(1,reg+1):
          if sheet.cell(row=2+i, column=15+n_count).value is None:
            sheet.cell(row=2+i, column=15+n_count).value = 0

        sheet["C29"] = "=SUM(C3:C28)"
        
        save_filename = f"紅白戦結果.xlsx"
        #wb.calculation_properties.fullCalcOnLoad = True
        book.save(save_filename)

        if yomikomi == 2:
            #保存
            output_stream = BytesIO()
            book.save(output_stream)
            output_stream.seek(0)

            try:
                df_result = pd.read_excel(output_stream, sheet_name='チーム分け結果詳細', header=1)
            except Exception as e:
                st.error(f"結果読み込み中にエラーが発生しました：{e}")
                st.download_button(
                    label="結果ファイルをダウンロード",
                    data=output_stream.getvalue(),
                    file_name=f"{uploaded_file.name}",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
                st.stop()


            #df_result = df_result.drop(index=0).reset_index(drop=True)
            df_result = df_result.drop(columns=df_result.columns[0])
            
            st.subheader("最適化結果（チーム分け結果）")
            def is_number(x):
                try:
                    float(x)
                    return True
                except:
                    return False



            if len(df_result) > 26:
                row_27 = df_result.iloc[[26]]
            else:
                row_27 = pd.DataFrame(columns=df_result.columns)
                
            mask_1 = df_result.iloc[:, 2].apply(is_number)
            cols_1 = [df_result.columns[0]] + list(df_result.columns[2:6])
            table_1 = df_result.loc[mask_1, cols_1]

            mask_2 = df_result.iloc[:, 6].apply(is_number)
            cols_2 = [df_result.columns[0]] + list(df_result.columns[7:11])
            table_2 = df_result.loc[mask_2, cols_2]

            
            #row_28 = df_result.iloc[[27], cols_1]

            table_1_with_second = pd.concat([table_1], ignore_index=True)

            
            table_2_with_second = pd.concat([table_2], ignore_index=True)

            table_1_with_second_clean = table_1_with_second.dropna(subset=[table_1_with_second.columns[1]])

            table_2_with_second_clean = table_2_with_second.dropna(subset=[table_2_with_second.columns[1]])
            df_display_2 = table_2_with_second_clean.drop(index=[26],errors = 'ignore')

            st.write("ポジション：その選手が守る守備位置（ピッチャー～ライト）")
            st.write("守備力：その選手のポジションでの守備の能力を数値化")
            st.write("打撃力：その選手の打撃の能力を数値化")
            st.write("総合力：その選手の守備力と打撃力の合計")

            st.subheader("チーム１に属する選手")
            st.write(f"チーム1　人数:{t1}、守備力合計:{p1}、打撃力合計:{b1}、総合力合計:{p1+b1}")
            st.dataframe(table_1_with_second_clean, use_container_width=True)

            st.subheader("チーム２に属する選手")
            st.write(f"チーム2　人数:{t2}、守備力合計:{p2}、打撃力合計:{b2}、総合力合計:{p2+b2}")
            st.dataframe(df_display_2, use_container_width=True)

            file_name = "紅白戦結果.xlsx"

            st.download_button(
                label="結果ファイルをダウンロード",
                data=output_stream,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        else:
            #保存
            output_stream = BytesIO()
            book.save(output_stream)
            output_stream.seek(0)

            try:
                df_result = pd.read_excel(output_stream, sheet_name='チーム分け結果詳細', header=1)
            except Exception as e:
                st.error(f"結果読み込み中にエラーが発生しました：{e}")
                st.download_button(
                    label="結果ファイルをダウンロード",
                    data=output_stream.getvalue(),
                    file_name=f"{uploaded_file.name}",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
                st.stop()

            #df_result = df_result.drop(index=0).reset_index(drop=True)
            df_result = df_result.drop(columns=df_result.columns[0])
            
            st.subheader("最適化結果（チーム分け結果）")
            def is_number(x):
                try:
                    float(x)
                    return True
                except:
                    return False

            


            if len(df_result) > 26:
                row_27 = df_result.iloc[[26]]
            else:
                row_27 = pd.DataFrame(columns=df_result.columns)
                
            mask_1 = df_result.iloc[:, 2].apply(is_number)
            cols_1 = [df_result.columns[0]] + list(df_result.columns[2:6])
            table_1 = df_result.loc[mask_1, cols_1]

            mask_2 = df_result.iloc[:, 6].apply(is_number)
            cols_2 = [df_result.columns[0]] + list(df_result.columns[7:11])
            table_2 = df_result.loc[mask_2, cols_2]

            
            #row_28 = df_result.iloc[[27], cols_1]

            table_1_with_second = pd.concat([table_1], ignore_index=True)

            
            table_2_with_second = pd.concat([table_2], ignore_index=True)

            table_1_with_second_clean = table_1_with_second.dropna(subset=[table_1_with_second.columns[1]])

            table_2_with_second_clean = table_2_with_second.dropna(subset=[table_2_with_second.columns[1]])
            df_display_2 = table_2_with_second_clean.drop(index=[26],errors = 'ignore')

            st.write("ポジション：その選手が守る守備位置（ピッチャー～ライト）")
            st.write("守備力：その選手のポジションでの守備の能力を数値化")
            st.write("打撃力：その選手の打撃の能力を数値化")
            st.write("総合力：その選手の守備力と打撃力の合計")
            
            st.subheader("チーム１に属する選手")
            st.write(f"チーム1　人数:{t1}、守備力合計:{p1}、打撃力合計:{b1}、総合力合計:{p1+b1}")
            st.dataframe(table_1_with_second_clean, use_container_width=True)

            st.subheader("チーム２に属する選手")
            st.write(f"チーム2　人数:{t2}、守備力合計:{p2}、打撃力合計:{b2}、総合力合計:{p2+b2}")
            st.dataframe(df_display_2, use_container_width=True)

            file_name = "紅白戦結果.xlsx"

            st.download_button(
                label="結果ファイルをダウンロード",
                data=output_stream,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        
      else:
        st.error("最適解が得られませんでした。")
